version: "3.8"

services:
#  backend:
#    build: .
#    ports:
#      - "50051:50051"

  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: account
      MYSQL_ROOT_PASSWORD: Headingto123/
